version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_gestion
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "1112:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
